### ISSUE TITLE
Actividades claves del modelo canvas

### ISSUE THREAD

**Issue by braianpalacio** [ProyectoTecnologicoIntegrador19/ProyectoTecnologicoIntegrador19#8]

**Comment by Evelyn-Masin** [comment]
[Proyecto integrador ACTIVIDADES CLAVE.docx](https://github.com/ProyectoTecnologicoIntegrador19/ProyectoTecnologicoIntegrador19/files/11729937/Proyecto.integrador.ACTIVIDADES.CLAVE.docx)
