### ISSUE TITLE
Estructura de costes del modelo canvas

### ISSUE THREAD

**Issue by braianpalacio** [ProyectoTecnologicoIntegrador19/ProyectoTecnologicoIntegrador19#9]

**Comment by g3rm6nI** [comment]
[Estructura de Costes.pdf](https://github.com/ProyectoTecnologicoIntegrador19/ProyectoTecnologicoIntegrador19/files/11715751/Estructura.de.Costes.pdf)
ESTRUCTURA DE COSTES
